	include "../include/registers.i"
	include "../include/vector.i"
	include "../include/beambits.i"
	include "../include/bplconbits.i"
	include "../include/blitter.i"
	include "hardware/dmabits.i"
	include "hardware/intbits.i"	
	include "constants.i"